rating:
  service:
    port: 8050
    image:
      name: vhung98vp/rating
      version: "1.1"
    database: 
      name: ratings
library:
  service:
    port: 8060
    image:
      name: vhung98vp/library
      version: "1.1"
    database: 
      name: libraries
reservation:
  service:
    port: 8070
    image:
      name: vhung98vp/reservation
      version: "1.1"
    database: 
      name: reservations
gateway:
  service:
    port: 8080
    image:
      name: vhung98vp/gateway
      version: "1.1"
    isGateway: true